// Japandi-voiced loading phrases — quiet, deliberate, often tactile.
// The agent is thinking; the phrasing should feel like someone attending
// to something small and careful rather than a machine grinding away.
export const SPINNER_PHRASES: string[] = [
  "Gathering wool",
  "Letting it steep",
  "Warming the cup",
  "Turning it over",
  "Finding the line",
  "Measuring twice",
  "Sharpening the pencil",
  "Pacing the hall",
  "Reading the room",
  "Holding the thread",
  "Listening for the shape",
  "Weighing the silence",
  "Smoothing the edges",
  "Tending the fire",
  "Minding the pause",
  "Gazing out the window",
  "Paging through the book",
  "Catching a breath",
  "Settling the dust",
  "Tracing the grain",
  "Polishing the thought",
  "Combing the possibilities",
  "Kneading the dough",
  "Brewing slowly",
  "Threading the needle",
  "Knotting the tie",
  "Unfolding the map",
  "Softening the corners",
  "Angling the light",
  "Arranging the room",
  "Taking a breath",
  "Fetching the water",
  "Cracking the book",
  "Letting the idea land",
  "Settling the mind",
  "Mending the line",
  "Hearing the river",
  "Choosing the word",
  "Finding the seam",
  "Watching the kettle",
  "Easing into it",
  "Sketching lightly",
  "Brushing off the moss",
  "Counting the petals",
  "Tending the embers",
  "Drawing the curtain",
  "Aligning the stones",
  "Folding the paper",
  "Sweeping the porch",
  "Turning the page",
  "Pouring slowly",
  "Breathing in",
  "Marking the place",
  "Wrapping the tea",
  "Pressing the leaves",
  "Tying the string",
  "Calming the current",
  "Mapping the quiet",
  "Watering the seed",
  "Stacking the stones",
  "Brushing the floor",
  "Laying the cloth",
  "Opening the window",
  "Stepping lightly",
  "Noticing the grain",
  "Holding the moment",
  "Wandering a little",
  "Rinsing the brush",
  "Listening to the room",
  "Drawing a slow circle",
  "Watching the light move",
  "Waiting for the water",
  "Pausing, on purpose",
  "Rehanging the scroll",
];
